
[env]
TERM = "tmux-256color"

[font]
size = 17

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
opacity = 0.9

[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
